### ISSUE TITLE
Support for version comments?

### ISSUE THREAD

**Issue by woodruffw** [stacklok/frizbee#167]
### Please describe the enhancement

First of all, thanks for this tool! I've been looking for something exactly like this.

`frizbee` overlaps nicely with CI-side workflow updaters, like Dependabot. Dependabot supports _version comments_ next to each hash-pinned workflow per https://github.com/dependabot/dependabot-core/issues/4691, like so:

```yaml
uses: example/example@longhash # v1.2.3
```

When Dependabot bumps `longhash`, it also rewrites the version comment to match the `git` tag for the new hash:

```yaml
uses: example/example@newhash # v1.2.4
```

It would be awesome if `frizbee` could *generate* these version comments, so that Dependabot (et al.) could use them.

### Solution Proposal

My proposal: `frizbee actions ...` should support generating a version comment next to each workflow reference that it transformed into a fully hashed reference.

Example input:

```yaml
uses: example/example@v1.2.3
```

Example output, with this new feature:

```yaml
uses: example/example@longhash # v1.2.3
```

This would be a behavioral change from the current default, so it _might_ make sense to keep it behind a `--add-version-comments` (or similar) option.

### Describe alternatives you've considered

The main alternative is to do nothing 🙂 -- Dependabot and other tools work fine without the comment; it's mostly there for human comprehension.

### Additional context

As mentioned above, https://github.com/dependabot/dependabot-core/issues/4691 is the original Dependabot tracker for this feature.

This version comment idiom also appears in OpenSSF's Scorecard and elsewhere.

### Acceptance Criteria

`frizbee actions` adds version comments while hash-pinning workflows!

**Comment by woodruffw** [comment]
NB: This requires editing YAML comments, which is a significant pain. So I understand not wanting to undertake implementing this, especially since it constrains the tool's ability to round-trip through a normal YAML parser 🙂

**Comment by rdimitrov** [comment]
hey @woodruffw, thanks for reaching out and happy to hear you find frizbee useful! 🚀 😃 

Can you share more details about which version of Frizbee you are using and if possible an example workflow file which we can use to reproduce this? 

Asking this because frizbee should already support it (link to the unit test - [replacer_test.go](https://github.com/stacklok/frizbee/blob/f85a8e4adf98169f9ead96851e0d135a1e30f493/pkg/replacer/replacer_test.go#L794)), but it's possible that you have hit some bug 😃

**Comment by woodruffw** [comment]
Whoops, I somehow completely missed this. I just tried `frizbee actions` again and it did indeed insert the comments I expected.

Sorry for the noise here, and thanks again for the fantastic tool!
