### ISSUE TITLE
Add support for docker compose

### ISSUE THREAD

**Issue by tranngoclam** [stacklok/frizbee#183]
### Please describe the enhancement

It would be great if Frizbee could support Docker Compose (docker-compose.yaml/yml, compose.yaml/yml files).

### Solution Proposal

Frizbee parse a docker compose files, for any image in each compose service, it finds the corresponding checksum and appends to each image tag accordingly.

**Comment by JAORMX** [comment]
@tranngoclam have you tried to do:

```
frizbee image compose.yaml
```

That should do the trick 😄

**Comment by tranngoclam** [comment]
Nice! That works, thanks @JAORMX
