### ISSUE TITLE
Set frizbee version to a release tag on release

### ISSUE THREAD

**Issue by jhrozek** [stacklok/frizbee#57]
This is a follow-up to PR #56 and issue #6 - it seems like the version would be set to dev even when we tag a release. It would be nicer to set the version in the [releaser workflow](https://github.com/stacklok/frizbee/blob/main/.github/workflows/releaser.yml#L66) as an environment variable and then take it into use in the [goreleaser dotfile](https://github.com/stacklok/frizbee/blob/main/.goreleaser.yaml#L12).

**Comment by jhrozek** [comment]
@kranurag7 thanks for your contribution earlier, it's much appreciated! Here's another issue if you're interested :-)

**Comment by kranurag7** [comment]
Hey, I created a patch here https://github.com/stacklok/frizbee/pull/58 

There is one thing that I'm not sure about. Why are we populating, `main.TreeState` if we don't have that variable of type string in the main package. 

I looked at some references, but I was not able to find something. 
- https://goreleaser.com/cookbooks/using-main.version/ 

Please let me know if I'm missing something here.
