### ISSUE TITLE
Add command for getting frizbee version

### ISSUE THREAD

**Issue by JAORMX** [stacklok/frizbee#6]
Doing `frizbee version` should output the binary's version.

**Comment by kranurag7** [comment]
@JAORMX would you be okay with one dependency from kubernetes upstream here? 

Ref: https://pkg.go.dev/sigs.k8s.io/release-utils/version#Version 
I got this approach by having a look at cosign repo. 

```bash
 $ ./frizbee version
  ___   ___   ___   ____  ___   ___   ___
 | __| | _ \ |_ _| |_  / | _ ) | __| | __|
 | _|  |   /  | |   / /  | _ \ | _|  | _|
 |_|   |_|_\ |___| /___| |___/ |___| |___|
frizbee: frizbee is a tool you may throw a tag at and it comes back with a checksum

GitVersion:    devel
GitCommit:     c72bf21b62943531f7ca7c4f5b7c4390d9f8b283
GitTreeState:  dirty
BuildDate:     2023-12-19T08:48:27
GoVersion:     go1.21.4
Compiler:      gc
Platform:      linux/amd64
```

**Comment by JAORMX** [comment]
@kranurag7 thanks for checking this out! I think we could do that. Though, a lighter-weight implementation would be ideal. Golang does have most of the necessary information on runtime: https://pkg.go.dev/runtime/debug#BuildInfo and we used something similar in minder: https://github.com/stacklok/minder/blob/main/internal/constants/version.go

What do you think about using a similar approach here instead?
