### ISSUE TITLE
Reformats the GH Actions workflow file, not just the "uses" lines

### ISSUE THREAD

**Issue by morganestes** [stacklok/frizbee#67]
### Describe the issue

When running the `ghactions` command, frizbee reformatted my YAML file in ways I didn't ask to or want. The docs say that it only touches the "uses" lines, but that's not the case.

The biggest issues are reformatting some (not all) inline shell scripts (removes all line breaks and makes the whole script a single line), rewriting emoji into Unicode strings, removing empty lines that I have in there for clarity, and removing spaces inside brackets. Basically, it forces its own coding style on my work without warning or any obvious way to prevent it.

### To Reproduce

- In a repo, with line spaces between workflow steps and/or spaces inside brackets, run `GITHUB_TOKEN=$(gh auth token) frizbee ghactions`.
- Run `git diff` and observe the reformatting of workflow files.

### What version are you using?

0.0.12

**Comment by JAORMX** [comment]
Thanks a lot for taking the time to submit this! I agree that it's unfortunate that it changes whitespaces within the file and it would be great if we would get that sorted.

For context, this is an issue with the fact we're using `gopkg.in/yaml.v3`. Apparently, other tools have had similar issues [1].

I'm open for suggestions on how to solve this, as I do think these whitespace changes are not a great user experience.

Thanks again for submitting this issue and checking frizbee out!

[1] https://github.com/kubernetes-sigs/kustomize/issues/3946

**Comment by jhrozek** [comment]
even if hacky, I wonder if a better user experience would be to just gather the `uses: ` substitutions and just substitute line for line without reassembling the YAML, since the `uses` lines are really just 1 line
